robot:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Effort Controllers ---------------------------------------
  left_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: LeftDrive
    pid: {p: 100, i: 0.01, d: 10.0}
    
  right_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: RightDrive
    pid: {p: 100, i: 0.01, d: 10.0}